erDiagram
    csip_record ||--|| referral : "was created by"
    csip_record ||--o{ audit_event : "changes tracked by"
    referral ||--o{ contributory_factor : "has contributory factors"
    referral ||--o| investigation : "optionally has an"
    referral ||--o| safer_custody_screening_outcome : "optionally has a"
    investigation ||--o{ interview : "can involve interviews with"
    referral ||--o| decisions_and_actions : "optionally has"
    csip_record ||--o| plan : "if decision is progress to CSIP"
    plan ||--o{ identified_need : "has one or more"
    plan ||--o{ review : "regularly reviewed"
    review ||--o{ attendee : "attended by"
    referral }o--|| incident_type : "incident categorised by"
    referral }o--|| incident_location : "incident occurred in"
    referral }o--|| area_of_work : "referer categorised by"
    referral }o--|| incident_involvement : "referred person was involved in the indecent as"
    safer_custody_screening_outcome }o--|| outcome : "outcome categorised by"
    interview }o--|| interviewee_role : "role of interviewee"
    decisions_and_actions }o--|| outcome : "outcome categorised by"
    decisions_and_actions }o--|| role : "role of person signing off the referral decision"
    contributory_factor }o--|| contributory_factor_type : "categorised by"

    csip_record {
        bigserial record_id PK "not null"
        uuid record_uuid "not null unique. Mapped to OFFENDER_CSIP_REPORTS"
        varchar(10) prison_number "not null"
        varchar(6) prison_code_when_recorded "Maps to OFFENDER_CSIP_REPORTS.AGY_LOC_ID"
        int sequence "not null. We could calculate this or delegate to sync"
        varchar(10) log_number "Maps to OFFENDER_CSIP_REPORTS.CSIP_SEQ"
        timestamp created_at "not null. Maps to OFFENDER_CSIP_REPORTS.CREATE_DATETIME"
        varchar(32) created_by "not null. Maps to OFFENDER_CSIP_REPORTS.CREATE_USER_ID"
        varchar(255) created_by_display_name "not null. Not mapped"
        timestamp last_modified_at "Maps to OFFENDER_CSIP_REPORTS.MODIFY_DATETIME"
        varchar(32) last_modified_by "Maps to OFFENDER_CSIP_REPORTS.MODIFY_USER_ID"
        varchar(255) last_modified_by_display_name "Not mapped"
    }

    referral {
        bigserial record_id PK "not null. Shared primary key with csip_record"
        date incident_date "not null. Maps to RFR_INCIDENT_DATE"
        time incident_time "Maps to OFFENDER_CSIP_REPORTS.RFR_INCIDENT_TIME"
        int incident_type_id FK "not null. FK to incident_type. Maps to OFFENDER_CSIP_REPORTS.RFR_INCIDENT_TYPE"
        int incident_location_id FK "not null. FK to incident_location. Maps to OFFENDER_CSIP_REPORTS.RFR_INCIDENT_LOCATION"
        varchar(240) referred_by "Maps to OFFENDER_CSIP_REPORTS."
        int referer_area_of_work_id FK "not null. FK to area_of_work. Maps to OFFENDER_CSIP_REPORTS.RFR_CSIP_FUNCTION"
        date referral_date "Maps to OFFENDER_CSIP_REPORTS.RFR_DATE_REPORTED"
        text referral_summary "Maps to OFFENDER_CSIP_REPORTS.RFR_COMMENT? 4000 character limit"
        boolean proactive_referral "Maps to OFFENDER_CSIP_REPORTS.RFR_PROACTIVE_RESPONSE where the default is 'N'"
        boolean staff_assaulted "Maps to OFFENDER_CSIP_REPORTS.RFR_STAFF_ASSAULTED where the default is 'N'"
        text assaulted_staff_name "Maps to OFFENDER_CSIP_REPORTS.RFR_STAFF_NAME. 1000 character limit"
        date release_date "Maps to OFFENDER_CSIP_REPORTS.CDR_RELEASE_DATE. Likely set by another screen in NOMIS"
        int incident_involvement_id FK "FK to incident_involvement. Maps to OFFENDER_CSIP_REPORTS.CDR_INVOLVEMENT"
        text description_of_concern "Maps to OFFENDER_CSIP_REPORTS.CDR_CONCERN_DESCRIPTION"
        text known_reasons "Maps to OFFENDER_CSIP_REPORTS.INV_KNOWN_REASONS"
        text other_information "Maps to OFFENDER_CSIP_REPORTS.CDR_OTHER_INFORMATION"
        boolean safer_custody_team_informed "Maps to OFFENDER_CSIP_REPORTS.CDR_SENT_DENT where the default is 'N'"
        boolean referral_complete "Maps to OFFENDER_CSIP_REPORTS.REFERRAL_COMPLETE_FLAG where the default is 'N'"
        varchar(32) referral_completed_by "Maps to OFFENDER_CSIP_REPORTS.REFERRAL_COMPLETED_BY"
        varchar(255) referral_completed_by_display_name "Not mapped"
        date referral_completed_date "Maps to OFFENDER_CSIP_REPORTS.REFERRAL_COMPLETED_DATE"
    }

    contributory_factor {
        bigserial contributory_factor_id PK "not null"
        uuid contributory_factor_uuid "not null unique. Mapped to OFFENDER_CSIP_FACTORS"
        bigserial record_id FK "not null"
        bigserial contributory_factor_type_id FK "not null. FK to contributory_factor_type. Mapped to OFFENDER_CSIP_FACTORS.CSIP_FACTOR"
        text comment "Maps to OFFENDER_CSIP_FACTORS.COMMENTS"
        timestamp created_at "not null. Maps to OFFENDER_CSIP_FACTORS.CREATE_DATETIME"
        varchar(32) created_by "not null. Maps to OFFENDER_CSIP_FACTORS.CREATE_USER_ID"
        varchar(255) created_by_display_name "not null. Not Mapped"
        timestamp last_modified_at "Maps to OFFENDER_CSIP_FACTORS.MODIFY_DATETIME"
        varchar(32) last_modified_by "Maps to OFFENDER_CSIP_FACTORS.MODIFY_USER_ID"
        varchar(255) last_modified_by_display_name "Not mapped"
    }

    safer_custody_screening_outcome {
        bigserial record_id PK "not null. Shared primary key with csip_record"
        int outcome_id "not null. FK to outcome. Maps to OFFENDER_CSIP_REPORTS.CDR_OUTCOME"
        varchar(100) recorded_by "not null. Maps to OFFENDER_CSIP_REPORTS.CDR_OUTCOME_RECORDED_BY"
        varchar(255) recorded_by_display_name "not null. Not mapped"
        date date "not null. Maps to OFFENDER_CSIP_REPORTS.CDR_OUTCOME_DATE"
        text reason_for_decision "Maps to OFFENDER_CSIP_REPORTS.CDR_DECISION_REASON. 4000 character limit"
    }

    investigation {
        bigserial record_id PK "not null. Shared primary key with csip_record"
        text staff_involved "Maps to OFFENDER_CSIP_REPORTS.INV_STAFF_INVOLVED. 4000 character limit"
        text evidence_secured "Maps to OFFENDER_CSIP_REPORTS.INV_EVIDENCE_SECURED. 4000 character limit"
        text occurrence_reason "Maps to OFFENDER_CSIP_REPORTS.INV_OCCURRENCE_REASON. 4000 character limit"
        text persons_usual_behaviour "Maps to OFFENDER_CSIP_REPORTS.INV_USUAL_BEHAVIOUR. 4000 character limit"
        text persons_trigger "Maps to OFFENDER_CSIP_REPORTS.INV_PERSONS_TRIGGER. 4000 character limit"
        text protective_factors "Maps to OFFENDER_CSIP_REPORTS.INV_PROTECTIVE_FACTORS. 4000 character limit"
    }

    interview {
        bigserial interview_id PK "not null"
        uuid interview_uuid "not null unique. Mapped to OFFENDER_CSIP_INTVW"
        bigserial record_id FK "not null"
        varchar(100) interviewee "not null. Person being interviewed (free text). Maps to OFFENDER_CSIP_INTVW.CSIP_INTERVIEWEE"
        date interview_date "Maps to OFFENDER_CSIP_INTVW.INTVW_DATE"
        int interviewee_role_id FK "not null. FK to interviewee_role. What role the interviewee played in the referral. Maps to OFFENDER_CSIP_INTVW.INTVW_ROLE"
        text interview_text "Maps to OFFENDER_CSIP_INTVW.COMMENTS. 4000 character limit"
        timestamp created_at "not null. Maps to OFFENDER_CSIP_INTVW.CREATE_DATETIME"
        varchar(32) created_by "not null. Maps to OFFENDER_CSIP_INTVW.CREATE_USER_ID"
        varchar(255) created_by_display_name "not null. Not mapped"
        timestamp last_modified_at "Maps to OFFENDER_CSIP_INTVW.MODIFY_DATETIME"
        varchar(32) last_modified_by "Maps to OFFENDER_CSIP_INTVW.MODIFY_USER_ID"
        varchar(255) last_modified_by_display_name "Not mapped"
    }

    decisions_and_actions {
        bigserial record_id PK "not null. Shared primary key with csip_record"
        text decision_conclusion "Maps to OFFENDER_CSIP_REPORTS.INV_CONCLUSION. 4000 character limit"
        int decision_outcome_id "not null. FK to outcome. Maps to OFFENDER_CSIP_REPORTS.INV_OUTCOME"
        int decision_outcome_signed_off_by_role_id "FK to role. Maps to OFFENDER_CSIP_REPORTS.INV_SIGNED_OFF_BY"
        varchar(100) decision_outcome_recorded_by "Maps to OFFENDER_CSIP_REPORTS.INV_OUTCOME_RECORDED_BY"
        varchar(255) decision_outcome_recorded_by_display_name "Not mapped"
        date decision_outcome_date "Maps to OFFENDER_CSIP_REPORTS.INV_OUTCOME_DATE"
        text next_steps "Maps to OFFENDER_CSIP_REPORTS.INV_NEXT_STEPS. 4000 character limit"
        boolean action_open_csip_alert "Maps to OFFENDER_CSIP_REPORTS.OPEN_CSIP_ALERT where the default is 'N'"
        boolean action_non_associations_updated "Maps to OFFENDER_CSIP_REPORTS.INV_NON_ASSOC_UPDATED where the default is 'N'"
        boolean action_observation_book "Maps to OFFENDER_CSIP_REPORTS.INV_OBSERVATION_BOOK where the default is 'N'"
        boolean action_unit_or_cell_move "Maps to OFFENDER_CSIP_REPORTS.INV_MOVE where the default is 'N'"
        boolean action_csra_or_rsra_review "Maps to OFFENDER_CSIP_REPORTS.INV_REVIEW where the default is 'N'"
        boolean action_service_referral "Maps to OFFENDER_CSIP_REPORTS.INV_SERVICE_REFERRAL where the default is 'N'"
        boolean action_sim_referral "Maps to OFFENDER_CSIP_REPORTS.INV_SIM_REFERRAL where the default is 'N'"
        text action_other "Maps to OFFENDER_CSIP_REPORTS.INV_OTHER. 4000 character limit"
    }

    plan {
        bigserial record_id PK "not null. Shared primary key with csip_record"
        varchar(100) case_manager "not null. Maps to OFFENDER_CSIP_REPORTS.CASE_MANAGER"
        varchar(240) reason_for_plan "not null. Maps to OFFENDER_CSIP_REPORTS.REASON"
        date case_review_date "not null. Maps to OFFENDER_CSIP_REPORTS.CASE_REV_DATE"
    }

    identified_need {
        bigserial identified_need_id PK "not null"
        uuid identified_need_uuid "not null unique. Mapped to OFFENDER_CSIP_PLANS"
        bigserial record_id FK "not null"
        text identified_need "Details of the need. Maps to OFFENDER_CSIP_PLANS.IDENTIFIED_NEED. 1000 character limit"
        varchar(100) need_identified_by "not null. Maps to OFFENDER_CSIP_PLANS.BY_WHOM. Who identified the need (free text)"
        date created_date "not null. Maps to OFFENDER_CSIP_PLANS.CREATE_DATE. Date the need was identified"
        date target_date "not null. Maps to OFFENDER_CSIP_PLANS.TARGET_DATE. Target date of the identified need"
        date closed_date "Date the identified need was closed. Maps to OFFENDER_CSIP_PLANS.CLOSED_DATE"
        text intervention "not null. The planned intervention. Maps to OFFENDER_CSIP_PLANS.INTERVENTION. 4000 character limit"
        text progression "How the plan is progressing. Maps to OFFENDER_CSIP_PLANS.PROGRESSION. 4000 character limit"
        timestamp created_at "not null. Maps to OFFENDER_CSIP_PLANS.CREATE_DATETIME"
        varchar(32) created_by "not null. Maps to OFFENDER_CSIP_PLANS.CREATE_USER_ID"
        varchar(255) created_by_display_name "not null. Not mapped"
        timestamp last_modified_at "Maps to OFFENDER_CSIP_PLANS.MODIFY_DATETIME"
        varchar(32) last_modified_by "Maps to OFFENDER_CSIP_PLANS.MODIFY_USER_ID"
        varchar(255) last_modified_by_display_name "Not mapped"
    }

    review {
        bigserial review_id PK "not null"
        uuid review_uuid "not null unique. Mapped to OFFENDER_CSIP_REVIEWS"
        bigserial record_id FK "not null"
        int review_sequence "not null. Maps to OFFENDER_CSIP_REVIEWS.REVIEW_SEQ"
        date review_date "Maps to OFFENDER_CSIP_REVIEWS.CREATE_DATE"
        varchar(32) recorded_by "not null. Maps to OFFENDER_CSIP_REVIEWS.CREATE_USER"
        varchar(255) recorded_by_display_name "not null. Not mapped"
        date next_review_date "Maps to OFFENDER_CSIP_REVIEWS.NEXT_REVIEW_DATE"
        boolean action_responsible_people_informed "Maps to OFFENDER_CSIP_REVIEWS.PEOPLE_INFORMED where the default is 'N'"
        boolean action_csip_updated "Maps to OFFENDER_CSIP_REVIEWS.CSIP_UPDATED where the default is 'N'"
        boolean action_remain_on_csip "Maps to OFFENDER_CSIP_REVIEWS.REMAIN_ON_CSIP where the default is 'N'"
        boolean action_case_note "Maps to OFFENDER_CSIP_REVIEWS.CASE_NOTE where the default is 'N'"
        boolean action_close_csip "Maps to OFFENDER_CSIP_REVIEWS.CLOSE_CSIP where the default is 'N'"
        date csip_closed_date "Maps to OFFENDER_CSIP_REVIEWS.CLOSE_DATE"
        text summary "Maps to OFFENDER_CSIP_REVIEWS.SUMMARY. 4000 character limit"
        timestamp created_at "not null. Maps to OFFENDER_CSIP_REVIEWS.CREATE_DATETIME"
        varchar(32) created_by "not null. Maps to OFFENDER_CSIP_REVIEWS.CREATE_USER_ID"
        varchar(255) created_by_display_name "not null. Not mapped"
        timestamp last_modified_at "Maps to OFFENDER_CSIP_REVIEWS.MODIFY_DATETIME"
        varchar(32) last_modified_by "Maps to OFFENDER_CSIP_REVIEWS.MODIFY_USER_ID"
        varchar(255) last_modified_by_display_name "Not mapped"
    }

    attendee {
        bigserial attendee_id PK "not null"
        uuid attendee_uuid "not null unique. Mapped to OFFENDER_CSIP_ATTENDEES"
        bigserial review_id FK "not null"
        varchar(100) name "Name of attendee/contributor. Maps to OFFENDER_CSIP_ATTENDEES.ATTENDEE_NAME"
        varchar(50) role "Role of attendee/contributor. Maps to OFFENDER_CSIP_ATTENDEES.ATTENDEE_ROLE"
        boolean attended "If attended (otherwise contributor). Maps to OFFENDER_CSIP_ATTENDEES.ATTENDED where the default is 'N'"
        text contribution "Free text description of attendee contribution. Maps to OFFENDER_CSIP_ATTENDEES.CONTRIBUTION. 4000 character limit"
        timestamp created_at "not null. Maps to OFFENDER_CSIP_ATTENDEES.CREATE_DATETIME"
        varchar(32) created_by "not null. Maps to OFFENDER_CSIP_ATTENDEES.CREATE_USER_ID"
        varchar(255) created_by_display_name "not null. Not mapped"
        timestamp last_modified_at "Maps to OFFENDER_CSIP_ATTENDEES.MODIFY_DATETIME"
        varchar(32) last_modified_by "Maps to OFFENDER_CSIP_ATTENDEES.MODIFY_USER_ID"
        varchar(255) last_modified_by_display_name "Not mapped"
    }

    audit_event {
        long id PK "not null"
        long csip_record_id FK "not null"
        varchar(40) action "not null"
        text description "not null"
        timestamp actioned_at "not null"
        varchar(32) actioned_by "not null"
        varchar(255) actioned_by_captured_name "not null"
        boolean recordAffected
        boolean referralAffected
        boolean contributoryFactorAffected
        boolean saferCustodyScreeningOutcomeAffected
        boolean investigationAffected
        boolean interviewAffected
        boolean decisionsAndActionsAffected
        boolean planAffected
        boolean identifiedNeedAffected
        boolean reviewAffected
        boolean attendeeAffected
    }

    incident_type {
        bigserial incident_type_id PK "not null"
        varchar(12) code "not null unique. The NOMIS reference data code for the CSIP_TYP domain"
        varchar(40) description
        int list_sequence
        timestamp created_at "not null"
        varchar(32) created_by "not null"
        timestamp last_modified_at
        varchar(32) last_modified_by
        timestamp deactivated_at
        varchar(32) deactivated_by
    }

    incident_location {
        bigserial incident_location_id PK "not null"
        varchar(40) code "not null unique. The NOMIS reference data code for the CSIP_LOC domain"
        varchar(40) description
        int list_sequence
        timestamp created_at "not null"
        varchar(32) created_by "not null"
        timestamp last_modified_at
        varchar(32) last_modified_by
        timestamp deactivated_at
        varchar(32) deactivated_by
    }

    area_of_work {
        bigserial area_of_work_id PK "not null"
        varchar(40) code "not null unique. The NOMIS reference data code for the CSIP_FUNC domain"
        varchar(40) description
        int list_sequence
        timestamp created_at "not null"
        varchar(32) created_by "not null"
        timestamp last_modified_at
        varchar(32) last_modified_by
        timestamp deactivated_at
        varchar(32) deactivated_by
    }

    incident_involvement {
        bigserial incident_involvement_id PK "not null"
        varchar(12) code "not null unique. The NOMIS reference data code for the CSIP_INV domain"
        varchar(40) description
        int list_sequence
        timestamp created_at "not null"
        varchar(32) created_by "not null"
        timestamp last_modified_at
        varchar(32) last_modified_by
        timestamp deactivated_at
        varchar(32) deactivated_by
    }

    contributory_factor_type {
        bigserial contributory_factor_type_id PK "not null"
        varchar(12) code "not null unique. The NOMIS reference data code for the CSIP_FAC domain"
        varchar(40) description
        int list_sequence
        timestamp created_at "not null"
        varchar(32) created_by "not null"
        timestamp last_modified_at
        varchar(32) last_modified_by
        timestamp deactivated_at
        varchar(32) deactivated_by
    }

    outcome {
        bigserial outcome_id PK "not null"
        varchar(12) code "not null unique. The NOMIS reference data code for the CSIP_OUT domain"
        varchar(40) description
        int list_sequence
        timestamp created_at "not null"
        varchar(32) created_by "not null"
        timestamp last_modified_at
        varchar(32) last_modified_by
        timestamp deactivated_at
        varchar(32) deactivated_by
    }

    interviewee_role {
        bigserial interviewee_role_id PK "not null"
        varchar(12) code "not null unique. The NOMIS reference data code for the CSIP_INTVROL domain"
        varchar(40) description
        int list_sequence
        timestamp created_at "not null"
        varchar(32) created_by "not null"
        timestamp last_modified_at
        varchar(32) last_modified_by
        timestamp deactivated_at
        varchar(32) deactivated_by
    }

    role {
        bigserial role_id PK "not null"
        varchar(12) code "not null unique. The NOMIS reference data code for the CSIP_ROLE domain"
        varchar(40) description
        int list_sequence
        timestamp created_at "not null"
        varchar(32) created_by "not null"
        timestamp last_modified_at
        varchar(32) last_modified_by
        timestamp deactivated_at
        varchar(32) deactivated_by
    }
