services:
  db:
    image: postgres:18
    networks:
      - hmpps
    container_name: csip-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=csip
      - POSTGRES_PASSWORD=csip
      - POSTGRES_USER=csip

  localstack:
    image: localstack/localstack:latest
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  hmpps:
