generic-service:
  nameOverride: hmpps-challenge-support-intervention-plan-api
  productId: "DPS094" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 2
  resources:
    requests:
      cpu: 128m
      memory: 768Mi

  image:
    repository: quay.io/hmpps/hmpps-challenge-support-intervention-plan-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-challenge-support-intervention-plan-api-cert

  # Used to access resources like S3 buckets, SQS queues and SNS topics
  serviceAccountName: hmpps-challenge-support-intervention-plan-api

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    DB_SSL_MODE: "verify-full"
    AWS_REGION: "eu-west-2"
    HMPPS_SQS_USE_WEB_TOKEN: "true"

    SENTRY_TRACES_SAMPLE_RATE: '0.05'
    SENTRY_IGNORED_EXCEPTIONS_FOR_TYPE: "org.apache.catalina.connector.ClientAbortException"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-challenge-support-intervention-plan-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      MANAGE_USERS_CLIENT_ID: "MANAGE_USERS_CLIENT_ID"
      MANAGE_USERS_CLIENT_SECRET: "MANAGE_USERS_CLIENT_SECRET"
      PRISONER_SEARCH_CLIENT_ID: "PRISONER_SEARCH_CLIENT_ID"
      PRISONER_SEARCH_CLIENT_SECRET: "PRISONER_SEARCH_CLIENT_SECRET"
      SENTRY_DSN: SENTRY_DSN
      SENTRY_AUTH_TOKEN: SENTRY_AUTH_TOKEN
    rds-postgresql-instance-output:
      DB_SERVER: "rds_instance_address"
      DB_NAME: "database_name"
      DB_USER: "database_username"
      DB_PASS: "database_password"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_HMPPSEVENTTOPIC_ARN: "topic_arn"
    sqs-domain-events-secret:
      HMPPS_SQS_QUEUES_HMPPSDOMAINEVENTSQUEUE_QUEUE_NAME: "queue_name"
    sqs-domain-events-dlq-secret:
      HMPPS_SQS_QUEUES_HMPPSDOMAINEVENTSQUEUE_DLQ_NAME: "queue_name"

  allowlist:
    groups:
      - digital_staff_and_mojo
      - moj_cloud_platform

generic-prometheus-alerts:
  targetApplication: hmpps-challenge-support-intervention-plan-api

generic-data-analytics-extractor:
  serviceAccountName: hmpps-csip-to-ap-s3
  databaseSecretName: rds-postgresql-instance-output
  destinationS3SecretName: analytical-platform-reporting-s3-bucket
  enabled: false
