---
# Per environment values which override defaults in hmpps-challenge-support-intervention-plan-api/values.yaml

generic-service:
  ingress:
    host: csip-api.hmpps.service.justice.gov.uk

  env:
    SENTRY_ENVIRONMENT: prod
    API_BASE_URL_HMPPS_AUTH: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_MANAGE_USERS: "https://manage-users-api.hmpps.service.justice.gov.uk"
    API_BASE_URL_PRISONER_SEARCH: "https://prisoner-search.prison.service.justice.gov.uk"
    EVENTS_PUBLISH: false
    EVENTS_BASE_URL: "https://csip-api.hmpps.service.justice.gov.uk"
    SERVICE_ACTIVE_PRISONS:
  postgresDatabaseRestore:
    enabled: true
    namespace_secrets:
      rds-postgresql-instance-output:
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
        DB_HOST: "rds_instance_address"
      rds-postgresql-instance-output-preprod:
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
        DB_HOST_PREPROD: "rds_instance_address"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-alerts-api-prod

generic-data-analytics-extractor:
  cronJobSchedule: "0 1 * * 1-5"