---
# Per environment values which override defaults in hmpps-challenge-support-intervention-plan-api/values.yaml

generic-service:

  ingress:
    host: csip-api-preprod.hmpps.service.justice.gov.uk

  env:
    SENTRY_ENVIRONMENT: preprod
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    SPRING_PROFILES_ACTIVE: preprod
    API_BASE_URL_HMPPS_AUTH: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_MANAGE_USERS: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    API_BASE_URL_PRISONER_SEARCH: "https://prisoner-search-preprod.prison.service.justice.gov.uk"
    SERVICE_BASE_URL: "https://csip-api-preprod.hmpps.service.justice.gov.uk"
    SERVICE_ACTIVE_PRISONS: "***"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: maintenance-alerts-non-prod-warning
  businessHoursOnly: true
  sqsOldestAlertQueueNames:
    - "hmpps-csip-preprod-domain_events_queue"
  sqsNumberAlertQueueNames:
    - "hmpps-csip-preprod-domain_events_dlq"
  sqsAlertsOldestThreshold: 10
  sqsAlertsTotalMessagesThreshold: 1
  rdsAlertsDatabases:
    cloud-platform-d4b8139eb1269041: 'CSIP DB'
  rdsAlertsConnectionThreshold: 100