---
# Per environment values which override defaults in hmpps-challenge-support-intervention-plan-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: csip-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    SPRING_PROFILES_ACTIVE: dev
    API_BASE_URL_HMPPS_AUTH: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_MANAGE_USERS: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    API_BASE_URL_PRISONER_SEARCH: "https://prisoner-search-dev.prison.service.justice.gov.uk"
    EVENTS_PUBLISH: false
    EVENTS_BASE_URL: "https://csip-api-dev.hmpps.service.justice.gov.uk"
    SERVICE_ACTIVE_PRISONS: "LEI"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: move-and-improve-alerts-non-prod
