---
# Per environment values which override defaults in hmpps-challenge-support-intervention-plan-api/values.yaml

generic-service:

  ingress:
    host: csip-api-dev.hmpps.service.justice.gov.uk

  scheduledDowntime:
    enabled: true

  env:
    SENTRY_ENVIRONMENT: dev
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    SPRING_PROFILES_ACTIVE: dev
    API_BASE_URL_HMPPS_AUTH: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_MANAGE_USERS: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    API_BASE_URL_PRISONER_SEARCH: "https://prisoner-search-dev.prison.service.justice.gov.uk"
    SERVICE_PUBLISH_EVENTS: true
    SERVICE_BASE_URL: "https://csip-api-dev.hmpps.service.justice.gov.uk"
    SERVICE_ACTIVE_PRISONS: "MDI,LEI,KMI"

  allowlist:
    groups:
      - digital_staff_and_mojo
      - moj_cloud_platform
      - prisons

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-alerts-api-non-prod
  businessHoursOnly: true

generic-data-analytics-extractor:
  enabled: true
  cronJobSchedule: "0 21 * * 1-5"
