CREATE TABLE case_notes_analysed
(
    id                               UUID PRIMARY KEY NOT NULL,
    request_id                       UUID NOT NULL,
    investigation_id                 UUID NOT NULL,
    prisoner_number                  VARCHAR(10) NOT NULL,
    case_note_id                     UUID NOT NULL,
    prompt_key                       VARCHAR(255),
    prompt_version                   INT,
    behaviour_type                   VARCHAR(30) NOT NULL,
    usual_behaviour_relevancy        INT NOT NULL DEFAULT 0,
    risks_and_triggers_relevancy     INT NOT NULL DEFAULT 0,
    protective_factors_relevancy     INT NOT NULL DEFAULT 0
);

COMMENT ON TABLE case_notes_analysed IS 'Machine generated analysis results over a person''s prison case notes, used to suggest content for the CSIP investigation screen. Each row captures the model output for one analysed case note and behaviour type.';
COMMENT ON COLUMN case_notes_analysed.id IS 'Primary key. Surrogate UUID with no business meaning. [Sensitivity: NONE]';
COMMENT ON COLUMN case_notes_analysed.request_id IS 'Identifier of the analysis request that produced this analysis. Groups rows generated by one run. [Sensitivity: NONE]';
COMMENT ON COLUMN case_notes_analysed.investigation_id IS 'Identifier of the CSIP investigation this analysis belongs to. Matches csip_record.record_id via correlation_id. [Sensitivity: NONE]';
COMMENT ON COLUMN case_notes_analysed.prisoner_number IS 'NOMIS offender number (noms id) of the person whose case notes were analysed. [Sensitivity: PERSONAL]';
COMMENT ON COLUMN case_notes_analysed.case_note_id IS 'Identifier of the source case note in the case notes service. This table holds a copy of analysis results for that note. [Sensitivity: NONE]';
COMMENT ON COLUMN case_notes_analysed.prompt_key IS 'Key of the prompt used to generate the analysis. Provenance only. [Sensitivity: NONE]';
COMMENT ON COLUMN case_notes_analysed.prompt_version IS 'Version of the prompt used to generate the analysis, so results from a superseded prompt can be identified. [Sensitivity: NONE]';
COMMENT ON COLUMN case_notes_analysed.behaviour_type IS 'What the model inferred the case note evidences about the person. One of RISKS_AND_TRIGGERS, USUAL_BEHAVIOUR_PRESENTATION, PROTECTIVE_FACTORS. This is a machine generated hypothesis offered to a caseworker, not a professional assessment or a recorded observation. [Sensitivity: SPECIAL-CATEGORY]';
COMMENT ON COLUMN case_notes_analysed.usual_behaviour_relevancy IS 'Relevancy score for usual behaviour presentation. [Sensitivity: SPECIAL-CATEGORY]';
COMMENT ON COLUMN case_notes_analysed.risks_and_triggers_relevancy IS 'Relevancy score for risks and triggers. [Sensitivity: SPECIAL-CATEGORY]';
COMMENT ON COLUMN case_notes_analysed.protective_factors_relevancy IS 'Relevancy score for protective factors. [Sensitivity: SPECIAL-CATEGORY]';

CREATE INDEX idx_case_notes_analysed_investigation_id ON case_notes_analysed(investigation_id);
CREATE INDEX idx_case_notes_analysed_prisoner_number ON case_notes_analysed(prisoner_number);
CREATE INDEX idx_case_notes_analysed_case_note_id ON case_notes_analysed(case_note_id);
