name: SchemaSpy on push

on:
  push:
    branches:
      - '**'

jobs:
  schema-spy:
    uses: ./.github/workflows/schema-spy.yml
    with:
      init_db_cli: './gradlew initialiseDatabase'
      database_name: 'csip'
      database_user: 'csip'
      database_password: 'csip'
      database_schema: 'public'
    secrets: inherit